services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000

    environment:
      APPWRITE_ENDPOINT: ${NEXT_PUBLIC_APPWRITE_ENDPOINT}
      APPWRITE_PROJECT_ID: ${NEXT_PUBLIC_APPWRITE_PROJECT}
      APPWRITE_KEY: ${NEXT_APPWRITE_KEY}
      SENTRY_DSN: ${SENTRY_DSN}
    volumes:
      - .:/app
      - node_modules_volume:/app/node_modules
      - ./node_modules:/app/node_modules:cached

volumes:
  node_modules_volume:
